use_frameworks!

platform :ios, '12.0'

target 'NXGallery_Example' do
  pod 'NXGallery', :path => '../'

  target 'NXGallery_Tests' do
    inherit! :search_paths

    pod "RxSwift"
    pod "RxCocoa"
    pod "RxSwiftExt"
    pod "ImageScrollView"
    
  end
end
